routes/web.php
<?php

Route::get('/login', function () {
    return view('auth.login');
});
Route::get('/style', function () {
    return view('body.style');
});

Auth::routes();

Route::group( ['middleware' => 'auth' ], function(){

    Route::get('/', function(){
      return view ('dashboard');
    })->name('home');

    //
    //  Users
    //

    // Resource Controller
    Route::resource('/users', 'userController');

    //Produce user form based on type
    Route::get('users/typeCreate/{type}', 'userController@typeCreate');

    //-----------------------------

    //
    //  CUSTOMERS
    //

    //view customer Contacts
    Route::get('/customers/createSingle', 'customerController@createSingle')->name('customers.createSingle');

    //view customer Contacts
    Route::get('/customers/listing', 'customerController@listing')->name('customers.listing');

    // Resource Controller
    Route::resource('/customers', 'customerController');

    //view customer Contacts
    Route::get('/customers/listing', 'customerController@listing')->name('customers.listing');

    //view customer Contacts
    Route::get('/customers/{id}/contacts', 'customerController@contacts')->name('customers.contacts');

    //update customer contacts
    Route::put('/customers/{id}/contacts', 'customerController@updateContact')->name('customers.contacts.update');

    //creation form for new customer contact
    Route::get('/customers/{id}/contacts/create', 'customerController@createContact')->name('customers.contacts.create');

    //change customer contact to Primary
    Route::put('/customers/{id}/contacts/master/{contactKey}', 'customerController@primaryContact')->name('customers.contacts.master');

    //Store customer Contact
    Route::post('/customers/{id}/contacts/create', 'customerController@storeContact')->name('customers.contacts.store');

    //remove customer contact
    Route::delete('/customers/{id}/contacts/{contactKey}', 'customerController@deleteContact')->name('customers.contacts.destroy');

    //show customer warranties
    Route::get('/customers/{id}/warranties', 'customerController@warranties');

    //-----------------------------

    //
    //  Addresses
    //

    //view customer Contacts
    Route::get('/addresses/{id}/json', 'addressController@json')->name('addresses.json');

    Route::get('/addresses/create', 'addressController@create')->name('addresses.create');

    Route::get('/addresses/{id}', 'addressController@index')->name('addresses.index');



    //view customer addresses
    Route::get('/customers/{id}/addresses', 'addressController@index')->name('customers.addresses');

    //creation form for new customer address
    Route::get('/customers/{id}/addresses/create', 'addressController@create')->name('customers.addresses.create');

    //update customer address
    Route::put('/customers/{id}/addresses', 'addressController@update')->name('customers.addresses.update');

    //Store customer address
    Route::post('/customers/{id}/addresses/create', 'addressController@store')->name('customers.address.store');

    //change customer address to master
    Route::put('/customers/{id}/addresses/master', 'addressController@masterAddress')->name('customers.address.master');

    //remove customer address
    Route::delete('/customers/{id}/addresses', 'addressController@destroy')->name('customers.addresses.destroy');

    //-----------------------------

    //
    //  Franchises
    //

    // Resource Controller
    Route::resource('/franchises', 'franchiseController');

    //-----------------------------

    //
    //  WARRANTIES
    //


    // Resource Controller
    Route::resource('/warranties', 'warrantyController');

    //Customer Creation with warranty redirect
    Route::get('/customers/create/{redirect}', 'warrantyController@warrantyCreateCustomer')->name('warranty.customer.create');

    //warranty form with new customer and addresses
    Route::get('warranties/create/newCustomer/{id}/{address}', 'warrantyController@warrantyNewCustomer');

    //Show Search View for Customers
    Route::get('warranties/create/customers', 'warrantyController@warrantyCustomer');

    //Show Type warranty type selector
    Route::get('/warranties/create/type', 'warrantyController@warrantyType');

    //Show Warranty Form of a specific type
    Route::get('/warranties/create/type/{type}', 'warrantyController@warrantyForm');

    //Search Customers
    Route::get('warranties/create/{type}', 'customerController@search');

    //Show Customer Addresses
    Route::get('/warranties/create/addresses/{id}', 'warrantyController@warrantyAddress');

    //-----------------------------

    //
    //  Projects
    //

    //Create: Select Customers
    Route::get('/projects/create', function(){
        session()->forget('project');
        return view('projects.customers');
    })->name("projects.create");

    Route::get('/projects/create/completed', function(){
        session()->forget('project');
        return view('projects.finish');
    });

    //Create: Select Address
    Route::get('/projects/create/{customer}/address', function($customer){
        return view('projects.addresses',compact('customer'));
    });

    //Create: Select Billing
    Route::get('/projects/create/{customer}/billing', function($customer){

            return view('projects.billing',compact('customer'));
    });

    //Create Warranty
    Route::get('/projects/create/warranty', function(){
        $types = array();
        session()->forget('project.types');
        session(['project.types' => $types]);
        return view('projects.warranty');
    });

    //Project Review
    Route::get('/projects/create/review', 'projectController@projectReview')->name('projectReview');

    //Session Storage
    Route::post('/projects/create/', 'projectController@sessionStorage')->name('sessionStorage');

    //Session Access
    Route::get('/projects/session/', 'projectController@sessionAccess')->name('sessionAccess');

    //Project Review
    Route::post('/projects/create/review', 'projectController@store')->name('projectSubmission');


    Route::get('/resources',function(){
        return Redirect::to("resources.php");
    });

    Route::get('/areports',function(){
        return Redirect::to("areports.php");
    });

    Route::get('/freports',function(){
        return Redirect::to("freports.php");
    });

    Route::get('/pdfTest', function(){
        $dompdf = new PDF();
        $view = view('pdf.reviewPage')->render();
        $dompdf = PDF::loadHTML("hello")->output();
        file_put_contents('public/doc1.pdf', $dompdf);

        $pdf = new FPDI();

$pageCount = $pdf->setSourceFile('public/doc1.pdf');
$pageId = $pdf->importPage(1);

$pdf->addPage();
$pdf->useImportedPage($pageId, 10, 10, 90);

$pdf->Output();


        $pdf->Output('page12.pdf');

        // return view('pdf.reviewPage');
    });

});

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <main class="app-body">
        <div class="page-header">
            <h2>Dashboard</h2>
        </div>
        <div class="dashboard-nav row">
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="{{ route('projects.create') }}">
                        <i class="fas fa-plus"></i>
                        <span>Create Warranty</span>
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="#">
                        <i class="fas fa-history"></i>
                        <span>Order History</span>
                    </a>
                </div>
            </div>
            @if(Auth::user()->hasType('A'))
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="{{route('franchises.index')}}">
                        <i class="fas fa-plus"></i>
                        <span>Add Franchise</span>
                    </a>
                </div>
            </div>
            @endif
            @if(Auth::user()->hasType('F'))
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="/freports.php">
                        <i class="fas fa-copy"></i>
                        <span>Franchise Reports</span>
                    </a>
                </div>
            </div>
            @endif
            @if(Auth::user()->hasType('A'))
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="#">
                        <i class="fas fa-edit"></i>
                        <span>Update or Transfer Warranties</span>
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="#">
                        <i class="fas fa-print"></i>
                        <span>Print Surveys</span>
                    </a>
                </div>
            </div>
            @endif
            @if(Auth::user()->hasType('A'))
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="/areports.php">
                        <i class="fas fa-copy"></i>
                        <span>Admin Reports</span>
                    </a>
                </div>
            </div>
            @endif
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="#">
                        <i class="fas fa-user-circle"></i>
                        <span>My Account</span>
                    </a>
                </div>
            </div>
            @if(Auth::user()->hasType('A'))
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="{{route('users.index')}}">
                        <i class="fas fa-users"></i>
                        <span>User Management</span>
                    </a>
                </div>
            </div>
            @endif
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="{{route('customers.listing')}}">
                        <i class="fas fa-users"></i>
                        <span>Customer Management</span>
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="box">
                    <a href="/resources.php">
                        <i class="fas fa-users"></i>
                        <span>Resources</span>
                    </a>
                </div>
            </div>
        </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/listing.blade.php
@extends('layouts.app')

@section('content')
        <div class="box">
            <a href="#" class="btn blue create">Create</a>
        </div>
        <div class="form-container"></div>
        <div class="page-header">
            <h2>{{$pageName}}</h2>
        </div>


        <div class="box">
            <div class="table-wrapper">
              <table class="display" style="width:100%">
                <thead>
                  <tr>
                    @foreach($headers as $header)
                      <th>{{$header}}</th>
                    @endforeach
                  </tr>
                </thead>
              </table>
            </div>
        </div>

@endsection
@section('scripts')
<script>
  $("table").DataTable( {
      destroy: true,
      data: {!! json_encode($data) !!},
      "bProcessing": true,
      destroy: true,
      DT_RowId: 'id',
      columns: {!! json_encode($columns) !!}
  });
  $("table").off("click").on("click", "tbody tr .edit", function(){
    var id = $(this).parent().parent().attr("id");
    var path = window.location.pathname;
    window.location.href = path+"/"+id;
});
  $(".create").off("click").on("click",function(){
    $(this).parent().addClass("hidden");
    $.ajax({
    method: "GET",
    url: window.location.pathname + "/create"
  })
  .done(function(data) {
    $(".form-container").toggleClass("box");
    $(".form-container").html(data)
  });
  });
</script>
@endsection

resources/views/listingWarranty.blade.php
@extends('layouts.app')

@section('content')
        <div class="box">
            <a href="{{route('warranties.create')}}" class="btn blue create">Create</a>
        </div>
        <div class="form-container"></div>
        <div class="page-header">
            <h2>{{$pageName}}</h2>
        </div>


        <div class="box">
            <div class="table-wrapper">
              <table class="display" style="width:100%">
                <thead>
                  <tr>
                    @foreach($headers as $header)
                      <th>{{$header}}</th>
                    @endforeach
                  </tr>
                </thead>
              </table>
            </div>
        </div>

@endsection
@section('scripts')
<script>
  $("table").DataTable( {
      destroy: true,
      data: {!! json_encode($data) !!},
      "bProcessing": true,
      destroy: true,
      DT_RowId: 'id',
      columns: {!! json_encode($columns) !!}
  });
  $("table").off("click").on("click", "tbody tr .edit", function(){
    var id = $(this).parent().parent().attr("id");
    var path = window.location.pathname;
    window.location.href = path+"/"+id;
});
</script>
@endsection

resources/views/warranty.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header">
    <h2>Create A Warranty</h2>
</div>
<div class="box">

    <section id="stepBox">
        <button id="searchCustomer" class="btn yellow">Search Existing Customer</button>
        <button id="createCustomer" class="btn yellow">Create A New Customer</button>
    </section>
    <hr>
    <h4 class="hidden">Customer: <span id="showCustomer"></span></h4>
    <h4 class="hidden">Address: <span id="showAddress"></span></h4>
    <section class="form-wrapper">
        <form id="warrantyCreation" class="hidden" method="POST" action="{{route('warranties.store')}}">
            {{ csrf_field() }}
            @if(isset($id))
            <input type="text" class="form-control hidden" name="customer" value="{{$id}}">
            @else
            <input type="text" class="form-control hidden" name="customer">
            @endif

            @if(isset($id))
            <input type="text" class="form-control hidden" name="address" value="{{$address}}">
            @else
            <input type="text" class="form-control hidden" name="address">
            @endif
            <div class="form-group{{ $errors->has('consultant') ? ' has-error' : '' }}">
              <label for="consultant" class="col-md-4 control-label">Sales Consultant</label>

              <div class="col-md-6">
                  <input id="consultant" type="text" class="form-control" name="consultant" value="{{ old('consultant') }}" required autofocus>

              </div>
            </div>

            <div class="form-group{{ $errors->has('Installer') ? ' has-error' : '' }}">
              <label for="Installer" class="col-md-4 control-label">Installer's Name</label>

              <div class="col-md-6">
                  <input id="Installer" type="text" class="form-control" name="Installer" value="{{ old('Installer') }}" required autofocus>

              </div>
            </div>

            <div class="form-group{{ $errors->has('date') ? ' has-error' : '' }}">
              <label for="date" class="col-md-4 control-label">Installation Date</label>

              <div class="col-md-6">
                  <input id="date" type="date" class="form-control" name="date" value="{{ old('date') }}" required autofocus>

              </div>
            </div>
            <div id="warrantyForm"></div>
        </form>
    </section>
    <section id="form-navigation">
        <button id="backButton" class="btn blue hidden">Back</button>
        <button id="nextButton" class="btn blue hidden">Next</button>
        <button id="submit" type="submit" form="warrantyCreation" class="btn blue hidden">Next</button>
        <button id="resetButton" class="btn yellow hidden">Reset</button>
    </section>
</div>


@endsection
@section('scripts')
    <script>
        $("#searchCustomer").off("click").on("click", function(){
            $.ajax({
            method: "GET",
            url: "/warranties/create/customers"
          })
          .done(function(data) {
              $("#stepBox").html(data);
              $("#nextButton").removeClass("hidden");
              $("#resetButton").removeClass("hidden");
          });
        });


        $("#resetButton").off("click").on("click",function(){
            location.reload();
        });
    </script>
    <script>
        $("#createCustomer").off("click").on("click", function(){
            $.ajax({
                method: "GET",
                url: "/customers/create/yes"
            })
            .done(function(data) {
                $("#stepBox").html(data);
            });
        });
    </script>
@endsection