routes/web.php
<?php

Route::get('/login', function () {
    return view('auth.login');
});
Route::get('/style', function () {
    return view('body.style');
});

Auth::routes();

Route::group( ['middleware' => 'auth' ], function(){

    Route::get('/', function(){
      return view ('dashboard');
    })->name('home');

    //
    //  Users
    //

    // Resource Controller
    Route::resource('/users', 'userController');

    //Produce user form based on type
    Route::get('users/typeCreate/{type}', 'userController@typeCreate');

    //-----------------------------

    //
    //  CUSTOMERS
    //

    //view customer Contacts
    Route::get('/customers/createSingle', 'customerController@createSingle')->name('customers.createSingle');

    //view customer Contacts
    Route::get('/customers/listing', 'customerController@listing')->name('customers.listing');

    // Resource Controller
    Route::resource('/customers', 'customerController');

    //view customer Contacts
    Route::get('/customers/listing', 'customerController@listing')->name('customers.listing');

    //view customer Contacts
    Route::get('/customers/{id}/contacts', 'customerController@contacts')->name('customers.contacts');

    //update customer contacts
    Route::put('/customers/{id}/contacts', 'customerController@updateContact')->name('customers.contacts.update');

    //creation form for new customer contact
    Route::get('/customers/{id}/contacts/create', 'customerController@createContact')->name('customers.contacts.create');

    //change customer contact to Primary
    Route::put('/customers/{id}/contacts/master/{contactKey}', 'customerController@primaryContact')->name('customers.contacts.master');

    //Store customer Contact
    Route::post('/customers/{id}/contacts/create', 'customerController@storeContact')->name('customers.contacts.store');

    //remove customer contact
    Route::delete('/customers/{id}/contacts/{contactKey}', 'customerController@deleteContact')->name('customers.contacts.destroy');

    //show customer warranties
    Route::get('/customers/{id}/warranties', 'customerController@warranties');

    //-----------------------------

    //
    //  Addresses
    //

    //view customer Contacts
    Route::get('/addresses/{id}/json', 'addressController@json')->name('addresses.json');

    Route::get('/addresses/create', 'addressController@create')->name('addresses.create');

    Route::get('/addresses/{id}', 'addressController@index')->name('addresses.index');



    //view customer addresses
    Route::get('/customers/{id}/addresses', 'addressController@index')->name('customers.addresses');

    //creation form for new customer address
    Route::get('/customers/{id}/addresses/create', 'addressController@create')->name('customers.addresses.create');

    //update customer address
    Route::put('/customers/{id}/addresses', 'addressController@update')->name('customers.addresses.update');

    //Store customer address
    Route::post('/customers/{id}/addresses/create', 'addressController@store')->name('customers.address.store');

    //change customer address to master
    Route::put('/customers/{id}/addresses/master', 'addressController@masterAddress')->name('customers.address.master');

    //remove customer address
    Route::delete('/customers/{id}/addresses', 'addressController@destroy')->name('customers.addresses.destroy');

    //-----------------------------

    //
    //  Franchises
    //

    // Resource Controller
    Route::resource('/franchises', 'franchiseController');

    //-----------------------------

    //
    //  WARRANTIES
    //


    // Resource Controller
    Route::resource('/warranties', 'warrantyController');

    //Customer Creation with warranty redirect
    Route::get('/customers/create/{redirect}', 'warrantyController@warrantyCreateCustomer')->name('warranty.customer.create');

    //warranty form with new customer and addresses
    Route::get('warranties/create/newCustomer/{id}/{address}', 'warrantyController@warrantyNewCustomer');

    //Show Search View for Customers
    Route::get('warranties/create/customers', 'warrantyController@warrantyCustomer');

    //Show Type warranty type selector
    Route::get('/warranties/create/type', 'warrantyController@warrantyType');

    //Show Warranty Form of a specific type
    Route::get('/warranties/create/type/{type}', 'warrantyController@warrantyForm');

    //Search Customers
    Route::get('warranties/create/{type}', 'customerController@search');

    //Show Customer Addresses
    Route::get('/warranties/create/addresses/{id}', 'warrantyController@warrantyAddress');

    //-----------------------------

    //
    //  Projects
    //

    //Create: Select Customers
    Route::get('/projects/create', function(){
        session()->forget('project');
        return view('projects.customers');
    })->name("projects.create");

    Route::get('/projects/create/completed', function(){
        session()->forget('project');
        return view('projects.finish');
    });

    //Create: Select Address
    Route::get('/projects/create/{customer}/address', function($customer){
        return view('projects.addresses',compact('customer'));
    });

    //Create: Select Billing
    Route::get('/projects/create/{customer}/billing', function($customer){

            return view('projects.billing',compact('customer'));
    });

    //Create Warranty
    Route::get('/projects/create/warranty', function(){
        $types = array();
        session()->forget('project.types');
        session(['project.types' => $types]);
        return view('projects.warranty');
    });

    //Project Review
    Route::get('/projects/create/review', 'projectController@projectReview')->name('projectReview');

    //Session Storage
    Route::post('/projects/create/', 'projectController@sessionStorage')->name('sessionStorage');

    //Session Access
    Route::get('/projects/session/', 'projectController@sessionAccess')->name('sessionAccess');

    //Project Review
    Route::post('/projects/create/review', 'projectController@store')->name('projectSubmission');


    Route::get('/resources',function(){
        return Redirect::to("resources.php");
    });

    Route::get('/areports',function(){
        return Redirect::to("areports.php");
    });

    Route::get('/freports',function(){
        return Redirect::to("freports.php");
    });

    Route::get('/pdfTest', function(){
        $dompdf = new PDF();
        $view = view('pdf.reviewPage')->render();
        $dompdf = PDF::loadHTML("hello")->output();
        file_put_contents('public/doc1.pdf', $dompdf);

        $pdf = new FPDI();

$pageCount = $pdf->setSourceFile('public/doc1.pdf');
$pageId = $pdf->importPage(1);

$pdf->addPage();
$pdf->useImportedPage($pageId, 10, 10, 90);

$pdf->Output();


        $pdf->Output('page12.pdf');

        // return view('pdf.reviewPage');
    });

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
  protected $fillable = [
      'customer_id','billing_id','address_id'
  ];
}

app/Http/Controllers/projectController.php
<?php

namespace App\Http\Controllers;
use App\Project;
use App\Customer;
use App\Address;
use App\Warranty;

use Illuminate\Support\Facades\Storage;

use Illuminate\Http\Request;

class projectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $session = session('project');
        $project = [];

        if($session['config']['customer'] === "existing"){
            $customerID = $session['customer']['id'];
        }
        if($session['config']['customer'] === "new"){
            $customerSession = $session['customer'];
            $temp = $customerSession['contact']['fName'].'-'.$customerSession['contact']['lName'];
            $contact[$temp]['fName'] = $customerSession['contact']['fName'];
            $contact[$temp]['lName'] = $customerSession['contact']['lName'];
            $contact[$temp]['email'] = $customerSession['contact']['email'];
            $contact[$temp]['phone'] = $customerSession['contact']['phone'];
            $contact[$temp]['type'] = "Primary";

            $customer['contacts'] = json_encode($contact);

            $customer['name'] = $customerSession['name'];

            $customer['franchise_id'] = $customerSession['franchise'];

            $customerID = Customer::create($customer)->id;

            $address['address'] = $customerSession['address']['street'];
            $address['city'] = $customerSession['address']['city'];
            $address['state'] = $customerSession['address']['state'];
            $address['zip'] = $customerSession['address']['zip'];
            $address['county'] = $customerSession['address']['county'];
            $address['type'] = 'M';
            $main['data'] = json_encode($address,true);
            $main['customer_id'] = $customerID;

            $addressID = Address::create($main)->id;
        }

        if($session['config']['address'] === "existing"){
            $addressID = $session['address']['id'];
        }

        if($session['config']['address'] === "new"){

            $address['address'] = $customerSession['address']['street'];
            $address['city'] = $customerSession['address']['city'];
            $address['state'] = $customerSession['address']['state'];
            $address['zip'] = $customerSession['address']['zip'];
            $address['county'] = $customerSession['address']['county'];
            $address['type'] = 'M';
            $main['data'] = json_encode($address,true);
            $main['customer_id'] = $customerID;

            $addressID = Address::create($main)->id;
        }

        if($session['config']['billing'] === "existing"){
            if($session['config']['billingAddress'] === "same"){
                $billingID = $addressID;
            }
            if($session['config']['billingAddress'] === "different"){
                $billingID = $session['billing']['id'];
            }
        }
        if($session['config']['billing'] === "new"){
            if($session['config']['billingAddress'] === "same"){
                $billingID = $addressID;
            }
            if($session['config']['billingAddress'] === "different"){
                $address['address'] = $customerSession['billing']['street'];
                $address['city'] = $customerSession['billing']['city'];
                $address['state'] = $customerSession['billing']['state'];
                $address['zip'] = $customerSession['billing']['zip'];
                $address['county'] = $customerSession['billing']['county'];
                $address['type'] = 'M';
                $main['data'] = json_encode($address,true);
                $main['customer_id'] = $customerID;billing;

                $billingID = Address::create($main)->id;
            }
        }

        $project['customer_id'] = $customerID;
        $project['address_id'] = $addressID;
        $project['billing_id'] = $billingID;


        $projectID = Project::create($project)->id;

        foreach($session['warranty'] as $key => $value){
            $warranty['customer_id'] = $customerID;
            $warranty['project_id'] = $projectID;
            $warranty['type'] = $key;

            $data = $value;
            unset($data['customer'],$data['type']);

            $warranty['data'] = json_encode($data,true);
            Warranty::create($warranty);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function sessionAccess()
    {
        return session('project');
    }

    public function projectReview()
    {
        $session = session('project');
        $data = [];
        $data['config'] = $session['config'];

        if($session['config']['customer'] === "existing"){
            $customerID = $session['customer']['id'];
            $customer = Customer::find($customerID);
            $json = json_decode($customer['contacts'],true);
            $customer['contacts'] = $json;
            $data['customer'] = $customer;
        }

        if($session['config']['customer'] === "new"){
            $data['customer'] = $session['customer'];

            $data['customer']['contacts'] = $session['customer']['contact'];
        }

        if($session['config']['address'] === "existing"){
            $addressID = $session['address']['id'];
            $address = Address::find($addressID);
            $json = json_decode($address['data'],true);
            $data['customer']['address'] = $json;
        }

        if($session['config']['address'] === "new"){
            $data['address'] = $session['customer']['address'];
        }
        if(isset($session['config']['billing'])){

            if($session['config']['billing'] === "existing"){
                $addressID = $session['billing']['id'];
                $data['billing'] = Address::find($addressID);
            }

            if($session['config']['billing'] === "new"){
                $data['billing'] = $session['customer']['billing'];
            }
        }

        foreach($session['types'] as $type){
            if($type['type'] === 'dmGutter'){
                $data['warrantys']['dmGutter'] = $session['warranty']['dmGutter'];
            }
            if($type['type'] === 'dmSiding'){
                $data['warrantys']['dmSiding'] = $session['warranty']['dmSiding'];
            }
            if($type['type'] === 'pvcGutter'){
                $data['warrantys']['pvcGutter'] = $session['warranty']['pvcGutter'];
            }
            if($type['type'] === 'pvcSiding'){
                $data['warrantys']['pvcSiding'] = $session['warranty']['pvcSiding'];
            }
            if($type['type'] === 'roofing'){
                $data['warrantys']['roofing'] = $session['warranty']['roofing'];
            }
        }

        return view('projects.review', compact('data'));

    }

    public function sessionStorage(Request $request)
    {
        if($request->type === "removeWarranty"){
            $warrantyType = $request->warranty;
            $warrantyType = 'project.warranty.'.$warrantyType;
            session()->forget($warrantyType);
            $types = session('project.types');
            foreach($types as $key => $type){
                if($type['type'] === $request->warranty){
                    unset($types[$key]);
                }
            }
            session(['project.types' => $types]);
        }

        if($request->type === "newCustomer"){
            session()->forget('project');
            session(['project.config.customer' => 'new']);
            session(['project.config.address' => 'new']);
            session(['project.config.billing' => 'new']);
            session(['project.config.billingAddress' => 'same']);

            session(['project.customer.name' => $request->name]);
            session(['project.customer.franchise' => $request->franchise]);

            session(['project.customer.contact.fName' => $request->fName]);
            session(['project.customer.contact.lName' => $request->lName]);
            session(['project.customer.contact.email' => $request->email]);
            session(['project.customer.contact.phone' => $request->phone]);

            session(['project.customer.address.street' => $request->address]);
            session(['project.customer.address.city' => $request->city]);
            session(['project.customer.address.state' => $request->state]);
            session(['project.customer.address.zip' => $request->zip]);
            session(['project.customer.address.county' => $request->county]);

            if($request->billing === "yes"){
                session(['project.customer.billing.street' => $request->address]);
                session(['project.customer.billing.city' => $request->city]);

resources/views/projects/addresses.blade.php
@extends('projects.create')

@section('formContent')
<h2>Project Address</h2>
<div class="table-wrapper">
    <table>
        <thead>
            <tr>
                <th>Street Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
            </tr>
        </thead>
    </table>
</div>
<select id="billing" class="form-control" name="billing" required autofocus>
    <option value="yes">Yes</option>
    <option value="no">No</option>
</select>
<div class="form-wrapper hidden">
    <form></form>
</div>
<button class="btn yellow" id="newAddress">Create A New Address</button>
<button class="btn yellow hidden" id="existingAddress">Use Existing Address</button>
<input type="hidden" id="addressID"/>


@endsection
@section('scripts')
    <script>
        // Pull Listing of Customers
        $.get( "/addresses/{{$customer}}/json", function( data ) {
            $("table").DataTable( {
                destroy: true,
                data: data,
                "bProcessing": true,
                destroy: true,
                DT_RowId: 'id',
                columns: [
                    { "data": "data.address" },
                    { "data": "data.city" },
                    { "data": "data.state" },
                    { "data": "data.zip" }
                ]
            });
        });

        //Add Customer ID to input
        $("table").off("click").on("click", 'tbody tr', function(){
            addressID = $(this).attr('id');

            $("table").children("tbody").children("tr").each(function(){
                if($(this).hasClass("selected")){
                    $(this).removeClass("selected");
                } else {
                    $(this).addClass("selected");
                }
            });

            if(addressID !== ""){
                $(this).addClass("selected");
                $("#addressID").val(addressID);
                $("#nextButton").removeClass("hidden");
            }

        });

        //Create New Customer Button click
        $("#newAddress").off("click").on("click",function(){
            $(this).addClass("hidden");
            $("#existingAddress").removeClass("hidden");
            $.get( "{{route('addresses.create')}}", function( data ) {
                $("form").html(data);
                $(".form-wrapper").removeClass("hidden");
                $(".table-wrapper").addClass("hidden");
                $("#nextButton").removeClass("hidden");
            });
        });

        //Return to Existing Customers
        $("#existingAddress").off("click").on("click",function(){
            $(this).addClass("hidden");
            $("#newAddress").removeClass("hidden");
            $(".table-wrapper").removeClass("hidden");
            $("form").html("");
            $(".form-wrapper").addClass("hidden");
            $("#nextButton").addClass("hidden");
            $.get( "/addresses/{{$customer}}", function( data ) {
                $("table").DataTable( {
                    destroy: true,
                    data: data,
                    "bProcessing": true,
                    destroy: true,
                    DT_RowId: 'id',
                    columns: [
                        { "data": "data.address" },
                        { "data": "data.city" },
                        { "data": "data.state" },
                        { "data": "data.zip" }
                    ]
                });
            });
        });

        //Next Button click
        $("#nextButton").off("click").on("click", function(){
            if($(".table-wrapper").hasClass("hidden")){
                if($("#billing").val() === "yes"){
                    url = "/projects/create/warranty/";
                } else {
                    url = "/projects/create/{{$customer}}/billing/"
                }
                data = $("form").serialize()+"&type=newAddress";
            }

            if($(".form-wrapper").hasClass("hidden")){
                if($("#billing").val() === "yes"){
                    url = "/projects/create/warranty/";
                } else {
                    url = "/projects/create/{{$customer}}/billing/"
                }
                data = "id="+$("#addressID").val()+"&billing="+$("#billing").val()+"&type=existingAddress";
            }
            $.ajax ({
                url: "{{route('sessionStorage')}}",
                data: data+"&_token={{ csrf_token() }}",
                type: "POST",
                success: function(){
                    window.location.href = url;
                }
            })
        });
    </script>
@endsection

resources/views/projects/billing.blade.php
@extends('projects.create')

@section('formContent')
<h2>Billing Address</h2>
@if($customer !== "0")
    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    <th>Street Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="form-wrapper hidden">
        <form></form>
    </div>
    <button class="btn yellow" id="newAddress">Create A New Billing Address</button>
    <button class="btn yellow hidden" id="existingAddress">Use Existing Billing Address</button>
    <input type="hidden" id="addressID"/>
@else
    <div class="table-wrapper hidden">
    </div>
    <div class="form-wrapper">
        <form></form>
    </div>
@endif



@endsection
@section('scripts')
    <script>
        @if($customer !== "0")
        // Pull Listing of Customers
        $.get( "/addresses/{{$customer}}/json", function( data ) {
            $("table").DataTable( {
                destroy: true,
                data: data,
                "bProcessing": true,
                destroy: true,
                DT_RowId: 'id',
                columns: [
                    { "data": "data.address" },
                    { "data": "data.city" },
                    { "data": "data.state" },
                    { "data": "data.zip" }
                ]
            });
        });
        @else
        $.get( "{{route('addresses.create')}}", function( data ) {
            $("form").html(data);
            $(".form-wrapper").removeClass("hidden");
            $(".table-wrapper").addClass("hidden");
            $("#nextButton").removeClass("hidden");
            $("select[name='billing']").parent().parent().addClass("hidden");
        });
        @endif

        //Add Customer ID to input
        $("table").off("click").on("click", 'tbody tr', function(){
            addressID = $(this).attr('id');

            $("table").children("tbody").children("tr").each(function(){
                if($(this).hasClass("selected")){
                    $(this).removeClass("selected");
                } else {
                    $(this).addClass("selected");
                }
            });

            if(addressID !== ""){
                $(this).addClass("selected");
                $("#addressID").val(addressID);
                $("#nextButton").removeClass("hidden");
            }

        });

        //Create New Customer Button click
        $("#newAddress").off("click").on("click",function(){
            $(this).addClass("hidden");
            $("#existingAddress").removeClass("hidden");
            $.get( "{{route('addresses.create')}}", function( data ) {
                $("form").html(data);
                $(".form-wrapper").removeClass("hidden");
                $(".table-wrapper").addClass("hidden");
                $("#nextButton").removeClass("hidden");
                $("select[name='billing']").parent().parent().addClass("hidden");
            });

        });

        //Return to Existing Customers
        $("#existingAddress").off("click").on("click",function(){
            $(this).addClass("hidden");
            $("#newAddress").removeClass("hidden");
            $(".table-wrapper").removeClass("hidden");
            $("form").html("");
            $(".form-wrapper").addClass("hidden");
            $("#nextButton").addClass("hidden");
            $.get( "/addresses/{{$customer}}", function( data ) {
                $("table").DataTable( {
                    destroy: true,
                    data: data,
                    "bProcessing": true,
                    destroy: true,
                    DT_RowId: 'id',
                    columns: [
                        { "data": "data.address" },
                        { "data": "data.city" },
                        { "data": "data.state" },
                        { "data": "data.zip" }
                    ]
                });
            });
        });

        //Next Button click
        $("#nextButton").off("click").on("click", function(){
            if($(".table-wrapper").hasClass("hidden")){
                console.log("hi");
                data = $("form").serialize()+"&type=newBilling";
                url = "/projects/create/warranty/";
            }

            if($(".form-wrapper").hasClass("hidden")){
                data = "id="+$("#addressID").val()+"&type=existingBilling";
                url = "/projects/create/warranty/";
            }
            $.ajax ({
                url: "{{route('sessionStorage')}}",
                data: data+"&_token={{ csrf_token() }}",
                type: "POST",
                success: function(response){
                    window.location.href = url;
                }
            })
        });
    </script>
@endsection

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header">
    <h2>Create A Project</h2>
</div>
<div class="box">
    <section id="formContent">
      @yield('formContent')
    </section>
    <section id="form-navigation">
        <button id="backButton" class="btn blue hidden">Back</button>
        <button id="nextButton" class="btn blue hidden">Next</button>
        <button id="submit" type="submit" form="warrantyCreation" class="btn blue hidden">Next</button>
        <button id="resetButton" class="btn yellow hidden">Reset</button>
    </section>
</div>


@endsection
@section('scripts')
    <script>
    </script>
@endsection

resources/views/projects/customers.blade.php
@extends('projects.create')

@section('formContent')
<h2>Customer</h2>
<div class="table-wrapper">
    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
            </tr>
        </thead>
    </table>
</div>
<div class="form-wrapper hidden">
    <form></form>
</div>
<button class="btn yellow" id="newCustomer">Create A New Customer</button>
<button class="btn yellow hidden" id="existingCustomer">Use Existing Customer</button>
<input type="hidden" id="customerID"/>


@endsection
@section('scripts')
    <script>
        // Pull Listing of Customers
        $.get( "{{route('customers.index')}}", function( data ) {
            $("table").DataTable( {
                destroy: true,
                data: data,
                "bProcessing": true,
                destroy: true,
                DT_RowId: 'id',
                columns: [
                    { "data": "name" }
                ]
            });
        });

        //Add Customer ID to input
        $("table").off("click").on("click", 'tbody tr', function(){
            customerID = $(this).attr('id');

            $("table").children("tbody").children("tr").each(function(){
                if($(this).hasClass("selected")){
                    $(this).removeClass("selected");
                } else {
                    $(this).addClass("selected");
                }
            });

            if(customerID !== ""){
                $(this).addClass("selected");
                $("#customerID").val(customerID);
                $("#nextButton").removeClass("hidden");
            }

        });

        //Create New Customer Button click
        $("#newCustomer").off("click").on("click",function(){
            $(this).addClass("hidden");
            $("#existingCustomer").removeClass("hidden");
            $.get( "{{route('customers.create')}}", function( data ) {
                $("form").html(data);
                $(".form-wrapper").removeClass("hidden");
                $(".table-wrapper").addClass("hidden");
                $("#nextButton").removeClass("hidden");
            });
        });

        //Return to Existing Customers
        $("#existingCustomer").off("click").on("click",function(){
            $(this).addClass("hidden");
            $("#newCustomer").removeClass("hidden");
            $(".table-wrapper").removeClass("hidden");
            $("form").html("");
            $(".form-wrapper").addClass("hidden");
            $("#nextButton").addClass("hidden");
            $.get( "{{route('customers.index')}}", function( data ) {
                $("table").DataTable( {
                    destroy: true,
                    data: data,
                    "bProcessing": true,
                    destroy: true,
                    DT_RowId: 'id',
                    columns: [
                        { "data": "name" }
                    ]
                });
            });
        });

        //Next Button click
        $("#nextButton").off("click").on("click", function(){
            if($(".table-wrapper").hasClass("hidden")){
                data = $("form").serialize()+"&type=newCustomer";
                if($("select[name='billing']").val() === "yes"){
                    url = "/projects/create/address/"
                } else {
                    url = "/projects/create/0/billing/"
                }

            }

            if($(".form-wrapper").hasClass("hidden")){
                data = "id="+$("#customerID").val()+"&type=existingCustomer";

                    url = "/projects/create/"+$("#customerID").val()+"/address"

            }
            $.ajax ({
                url: "{{route('sessionStorage')}}",
                data: data+"&_token={{ csrf_token() }}",
                type: "POST",
                success: function(){
                    window.location.href = url;
                }
            })
        });
    </script>
@endsection

resources/views/projects/finish.blade.php
@extends('projects.create')

@section('formContent')
    <h3>Thank You For Your Submission</h3>
    <button id="again" class="btn green">Create Another Project</button>
    <button id="dashboard" class="btn green">Back To Dashboard</button>
@endsection

@section('scripts')
<script>
$("#again").off("click").on("click",function(){
    window.location.href = "/projects/create";
});
</script>
@endsection