routes/web.php
<?php

Route::get('/login', function () {
    return view('auth.login');
});
Route::get('/style', function () {
    return view('body.style');
});

Auth::routes();

Route::group( ['middleware' => 'auth' ], function(){

    Route::get('/', function(){
      return view ('dashboard');
    })->name('home');

    //
    //  Users
    //

    // Resource Controller
    Route::resource('/users', 'userController');

    //Produce user form based on type
    Route::get('users/typeCreate/{type}', 'userController@typeCreate');

    //-----------------------------

    //
    //  CUSTOMERS
    //

    //view customer Contacts
    Route::get('/customers/createSingle', 'customerController@createSingle')->name('customers.createSingle');

    //view customer Contacts
    Route::get('/customers/listing', 'customerController@listing')->name('customers.listing');

    // Resource Controller
    Route::resource('/customers', 'customerController');

    //view customer Contacts
    Route::get('/customers/listing', 'customerController@listing')->name('customers.listing');

    //view customer Contacts
    Route::get('/customers/{id}/contacts', 'customerController@contacts')->name('customers.contacts');

    //update customer contacts
    Route::put('/customers/{id}/contacts', 'customerController@updateContact')->name('customers.contacts.update');

    //creation form for new customer contact
    Route::get('/customers/{id}/contacts/create', 'customerController@createContact')->name('customers.contacts.create');

    //change customer contact to Primary
    Route::put('/customers/{id}/contacts/master/{contactKey}', 'customerController@primaryContact')->name('customers.contacts.master');

    //Store customer Contact
    Route::post('/customers/{id}/contacts/create', 'customerController@storeContact')->name('customers.contacts.store');

    //remove customer contact
    Route::delete('/customers/{id}/contacts/{contactKey}', 'customerController@deleteContact')->name('customers.contacts.destroy');

    //show customer warranties
    Route::get('/customers/{id}/warranties', 'customerController@warranties');

    //-----------------------------

    //
    //  Addresses
    //

    //view customer Contacts
    Route::get('/addresses/{id}/json', 'addressController@json')->name('addresses.json');

    Route::get('/addresses/create', 'addressController@create')->name('addresses.create');

    Route::get('/addresses/{id}', 'addressController@index')->name('addresses.index');



    //view customer addresses
    Route::get('/customers/{id}/addresses', 'addressController@index')->name('customers.addresses');

    //creation form for new customer address
    Route::get('/customers/{id}/addresses/create', 'addressController@create')->name('customers.addresses.create');

    //update customer address
    Route::put('/customers/{id}/addresses', 'addressController@update')->name('customers.addresses.update');

    //Store customer address
    Route::post('/customers/{id}/addresses/create', 'addressController@store')->name('customers.address.store');

    //change customer address to master
    Route::put('/customers/{id}/addresses/master', 'addressController@masterAddress')->name('customers.address.master');

    //remove customer address
    Route::delete('/customers/{id}/addresses', 'addressController@destroy')->name('customers.addresses.destroy');

    //-----------------------------

    //
    //  Franchises
    //

    // Resource Controller
    Route::resource('/franchises', 'franchiseController');

    //-----------------------------

    //
    //  WARRANTIES
    //


    // Resource Controller
    Route::resource('/warranties', 'warrantyController');

    //Customer Creation with warranty redirect
    Route::get('/customers/create/{redirect}', 'warrantyController@warrantyCreateCustomer')->name('warranty.customer.create');

    //warranty form with new customer and addresses
    Route::get('warranties/create/newCustomer/{id}/{address}', 'warrantyController@warrantyNewCustomer');

    //Show Search View for Customers
    Route::get('warranties/create/customers', 'warrantyController@warrantyCustomer');

    //Show Type warranty type selector
    Route::get('/warranties/create/type', 'warrantyController@warrantyType');

    //Show Warranty Form of a specific type
    Route::get('/warranties/create/type/{type}', 'warrantyController@warrantyForm');

    //Search Customers
    Route::get('warranties/create/{type}', 'customerController@search');

    //Show Customer Addresses
    Route::get('/warranties/create/addresses/{id}', 'warrantyController@warrantyAddress');

    //-----------------------------

    //
    //  Projects
    //

    //Create: Select Customers
    Route::get('/projects/create', function(){
        session()->forget('project');
        return view('projects.customers');
    })->name("projects.create");

    Route::get('/projects/create/completed', function(){
        session()->forget('project');
        return view('projects.finish');
    });

    //Create: Select Address
    Route::get('/projects/create/{customer}/address', function($customer){
        return view('projects.addresses',compact('customer'));
    });

    //Create: Select Billing
    Route::get('/projects/create/{customer}/billing', function($customer){

            return view('projects.billing',compact('customer'));
    });

    //Create Warranty
    Route::get('/projects/create/warranty', function(){
        $types = array();
        session()->forget('project.types');
        session(['project.types' => $types]);
        return view('projects.warranty');
    });

    //Project Review
    Route::get('/projects/create/review', 'projectController@projectReview')->name('projectReview');

    //Session Storage
    Route::post('/projects/create/', 'projectController@sessionStorage')->name('sessionStorage');

    //Session Access
    Route::get('/projects/session/', 'projectController@sessionAccess')->name('sessionAccess');

    //Project Review
    Route::post('/projects/create/review', 'projectController@store')->name('projectSubmission');


    Route::get('/resources',function(){
        return Redirect::to("resources.php");
    });

    Route::get('/areports',function(){
        return Redirect::to("areports.php");
    });

    Route::get('/freports',function(){
        return Redirect::to("freports.php");
    });

    Route::get('/pdfTest', function(){
        $dompdf = new PDF();
        $view = view('pdf.reviewPage')->render();
        $dompdf = PDF::loadHTML("hello")->output();
        file_put_contents('public/doc1.pdf', $dompdf);

        $pdf = new FPDI();

$pageCount = $pdf->setSourceFile('public/doc1.pdf');
$pageId = $pdf->importPage(1);

$pdf->addPage();
$pdf->useImportedPage($pageId, 10, 10, 90);

$pdf->Output();


        $pdf->Output('page12.pdf');

        // return view('pdf.reviewPage');
    });

});

resources/views/forms/contactCreate.blade.php
<div class="form-wrapper">
  <form id="main-form" class="" method="POST" action="{{route('customers.contacts.store', ['id' => $id])}}">
      {{ csrf_field() }}

      <div class="form-group{{ $errors->has('fName') ? ' has-error' : '' }}">
          <label for="fName" class="col-md-4 control-label">First Name</label>

          <div class="col-md-6">
              <input id="fName" type="text" class="form-control" name="fName" value="{{ old('fName') }}" required autofocus>

          </div>
      </div>

      <div class="form-group{{ $errors->has('lName') ? ' has-error' : '' }}">
          <label for="lName" class="col-md-4 control-label">Last Name</label>

          <div class="col-md-6">
              <input id="lName" type="text" class="form-control" name="lName" value="{{ old('lName') }}" required autofocus>

          </div>
      </div>

      <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
          <label for="email" class="col-md-4 control-label">Email</label>

          <div class="col-md-6">
              <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

          </div>
      </div>

      <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
          <label for="phone" class="col-md-4 control-label">Phone</label>

          <div class="col-md-6">
              <input id="phone" type="number" class="form-control" name="phone" value="{{ old('phone') }}" required autofocus>

          </div>
      </div>

      <div class="form-control">
          <button type="button" class="btn yellow cancel">Cancel</button>
          <button type="submit" form="main-form" class="btn green">Submit</button>
      </div>

  </form>
</div>
<script>
    $(".cancel").off("click").on("click", function(){
        location.reload();
    });
</script>

resources/views/forms/customerCreate.blade.php
<div class="form-wrapper">
  <form id="main-form" class="" method="POST" action="{{ route('customers.store') }}">
      {{ csrf_field() }}

      @if(isset($redirect))
          <input id="redirect" type="text" class="hidden" name="redirect" value="yes" required>
      @endif
      @if(Auth::user()->hasType('A'))
      <div class="form-group{{ $errors->has('franchise') ? ' has-error' : '' }}">
          <label for="franchise" class="col-md-4 control-label">Franchise</label>

          <div class="col-md-6">
              <select id="franchise" class="form-control" name="franchise" required autofocus>
                  @foreach($franchises as $franchise)
                    <option value="{{$franchise['id']}}">{{$franchise['name']}}</option>
                  @endforeach
              </select>

              @if ($errors->has('franchise'))
                  <span class="help-block">
                      <strong>{{ $errors->first('franchise') }}</strong>
                  </span>
              @endif
          </div>
      </div>
      @elseif(Auth::user()->hasType('F'))
      <div class="hidden form-group{{ $errors->has('franchise') ? ' has-error' : '' }}">
          <label for="franchise" class="col-md-4 control-label">Franchise</label>

          <div class="col-md-6">
              <select id="franchise" class="form-control" name="franchise" required autofocus>
                    <option value="{{Auth::user()->getFranchise()}}"></option>
              </select>
          </div>
      </div>
      @endif
      <div class="form-group{{ $errors->has('fName') ? ' has-error' : '' }}">
          <label for="nname" class="col-md-4 control-label">Customer Name</label>

          <div class="col-md-6">
              <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

              @if ($errors->has('name'))
                  <span class="help-block">
                      <strong>{{ $errors->first('name') }}</strong>
                  </span>
              @endif
          </div>
      </div>
      <hr>
      <h4>Primary Contact</h4>
      <div class="form-group{{ $errors->has('fName') ? ' has-error' : '' }}">
          <label for="fName" class="col-md-4 control-label">First Name</label>

          <div class="col-md-6">
              <input id="fName" type="text" class="form-control" name="fName" value="{{ old('fName') }}" required autofocus>

              @if ($errors->has('fName'))
                  <span class="help-block">
                      <strong>{{ $errors->first('fName') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('lName') ? ' has-error' : '' }}">
          <label for="lName" class="col-md-4 control-label">Last Name</label>

          <div class="col-md-6">
              <input id="lName" type="text" class="form-control" name="lName" value="{{ old('lName') }}" required autofocus>

              @if ($errors->has('lName'))
                  <span class="help-block">
                      <strong>{{ $errors->first('lName') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
          <label for="email" class="col-md-4 control-label">Email</label>

          <div class="col-md-6">
              <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

              @if ($errors->has('email'))
                  <span class="help-block">
                      <strong>{{ $errors->first('email') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
          <label for="phone" class="col-md-4 control-label">Phone</label>

          <div class="col-md-6">
              <input id="phone" type="phone" class="form-control" name="phone" value="{{ old('phone') }}" required autofocus>

              @if ($errors->has('phone'))
                  <span class="help-block">
                      <strong>{{ $errors->first('phone') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <hr>
      <h4>Primary Location</h4>
      <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
          <label for="address" class="col-md-4 control-label">Address</label>

          <div class="col-md-6">
              <input id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" required autofocus>

              @if ($errors->has('address'))
                  <span class="help-block">
                      <strong>{{ $errors->first('address') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
          <label for="city" class="col-md-4 control-label">City</label>

          <div class="col-md-6">
              <input id="city" type="text" class="form-control" name="city" value="{{ old('city') }}" required autofocus>

              @if ($errors->has('city'))
                  <span class="help-block">
                      <strong>{{ $errors->first('city') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('state') ? ' has-error' : '' }}">
          <label for="state" class="col-md-4 control-label">State</label>

          <div class="col-md-6">
              <select id="state" class="form-control" name="state" required autofocus>
                  <option value="AL">Alabama</option>
                  <option value="AK">Alaska</option>
                  <option value="AZ">Arizona</option>
                  <option value="AR">Arkansas</option>
                  <option value="CA">California</option>
                  <option value="CO">Colorado</option>
                  <option value="CT">Connecticut</option>
                  <option value="DE">Delaware</option>
                  <option value="DC">District Of Columbia</option>
                  <option value="FL">Florida</option>
                  <option value="GA">Georgia</option>
                  <option value="HI">Hawaii</option>
                  <option value="ID">Idaho</option>
                  <option value="IL">Illinois</option>
                  <option value="IN">Indiana</option>
                  <option value="IA">Iowa</option>
                  <option value="KS">Kansas</option>
                  <option value="KY">Kentucky</option>
                  <option value="LA">Louisiana</option>
                  <option value="ME">Maine</option>
                  <option value="MD">Maryland</option>
                  <option value="MA">Massachusetts</option>
                  <option value="MI">Michigan</option>
                  <option value="MN">Minnesota</option>
                  <option value="MS">Mississippi</option>
                  <option value="MO">Missouri</option>
                  <option value="MT">Montana</option>
                  <option value="NE">Nebraska</option>
                  <option value="NV">Nevada</option>
                  <option value="NH">New Hampshire</option>
                  <option value="NJ">New Jersey</option>
                  <option value="NM">New Mexico</option>
                  <option value="NY">New York</option>
                  <option value="NC">North Carolina</option>
                  <option value="ND">North Dakota</option>
                  <option value="OH">Ohio</option>
                  <option value="OK">Oklahoma</option>
                  <option value="OR">Oregon</option>
                  <option value="PA">Pennsylvania</option>
                  <option value="RI">Rhode Island</option>
                  <option value="SC">South Carolina</option>
                  <option value="SD">South Dakota</option>
                  <option value="TN">Tennessee</option>
                  <option value="TX">Texas</option>
                  <option value="UT">Utah</option>
                  <option value="VT">Vermont</option>
                  <option value="VA">Virginia</option>
                  <option value="WA">Washington</option>
                  <option value="WV">West Virginia</option>
                  <option value="WI">Wisconsin</option>
                  <option value="WY">Wyoming</option>
              </select>

              @if ($errors->has('state'))
                  <span class="help-block">
                      <strong>{{ $errors->first('state') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('zip') ? ' has-error' : '' }}">
          <label for="zip" class="col-md-4 control-label">Zip</label>

          <div class="col-md-6">
              <input id="zip" type="text" class="form-control" name="zip" value="{{ old('zip') }}" required autofocus>

              @if ($errors->has('zip'))
                  <span class="help-block">
                      <strong>{{ $errors->first('zip') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('county') ? ' has-error' : '' }}">
          <label for="county" class="col-md-4 control-label">County</label>

          <div class="col-md-6">
              <input id="county" type="text" class="form-control" name="county" value="{{ old('county') }}" required autofocus>

              @if ($errors->has('county'))
                  <span class="help-block">
                      <strong>{{ $errors->first('county') }}</strong>
                  </span>
              @endif
          </div>
      </div>



      @if(!isset($type))
      <div class="form-control">
          <button type="button" class="btn yellow cancel">Cancel</button>
          <button type="submit" form="main-form" class="btn green">Submit</button>
      </div>
      @endif

  </form>
</div>
<script>
$(".cancel").off("click").on("click", function(){
  $(".form-container").prev().removeClass("hidden");
  $(".form-container").removeClass("box");
  $(".form-container").html("");
});
</script>
@if(isset($redirect))
<script>
$(".cancel").off("click").on("click", function(){
  window.location.href='/warranties/create';
});
</script>
@endif

resources/views/forms/franchiseCreate.blade.php
@if(!isset($type))
<h3 class="box-header">New Franchise Form</h3>
@endif
<div class="form-wrapper">
  <form id="main-form" class="" method="POST" action="{{ route('franchises.store') }}">
      {{ csrf_field() }}

      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
          <label for="name" class="col-md-4 control-label">Franchise Name</label>

          <div class="col-md-6">
              <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

              @if ($errors->has('name'))
                  <span class="help-block">
                      <strong>{{ $errors->first('name') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
          <label for="username" class="col-md-4 control-label">User Name</label>

          <div class="col-md-6">
              <input id="username" class="form-control" name="username" value="{{ old('username') }}" required>

              @if ($errors->has('username'))
                  <span class="help-block">
                      <strong>{{ $errors->first('username') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
          <label for="password" class="col-md-4 control-label">Password</label>

          <div class="col-md-6">
              <input id="password" type="password" class="form-control" name="password" required>

              @if ($errors->has('password'))
                  <span class="help-block">
                      <strong>{{ $errors->first('password') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group">
          <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

          <div class="col-md-6">
              <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
          </div>
      </div>



      <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
          <label for="address" class="col-md-4 control-label">Address</label>

          <div class="col-md-6">
              <input id="address" class="form-control" name="address" value="{{ old('address') }}" required>

              @if ($errors->has('address'))
                  <span class="help-block">
                      <strong>{{ $errors->first('address') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
          <label for="city" class="col-md-4 control-label">City</label>

          <div class="col-md-6">
              <input id="city" class="form-control" name="city" value="{{ old('city') }}" required>

              @if ($errors->has('city'))
                  <span class="help-block">
                      <strong>{{ $errors->first('city') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('state') ? ' has-error' : '' }}">
          <label for="state" class="col-md-4 control-label">State</label>

          <div class="col-md-6">
              <select id="state" class="form-control" name="state" required>
                	<option value="AL">Alabama</option>
                	<option value="AK">Alaska</option>
                	<option value="AZ">Arizona</option>
                	<option value="AR">Arkansas</option>
                	<option value="CA">California</option>
                	<option value="CO">Colorado</option>
                	<option value="CT">Connecticut</option>
                	<option value="DE">Delaware</option>
                	<option value="DC">District Of Columbia</option>
                	<option value="FL">Florida</option>
                	<option value="GA">Georgia</option>
                	<option value="HI">Hawaii</option>
                	<option value="ID">Idaho</option>
                	<option value="IL">Illinois</option>
                	<option value="IN">Indiana</option>
                	<option value="IA">Iowa</option>
                	<option value="KS">Kansas</option>
                	<option value="KY">Kentucky</option>
                	<option value="LA">Louisiana</option>
                	<option value="ME">Maine</option>
                	<option value="MD">Maryland</option>
                	<option value="MA">Massachusetts</option>
                	<option value="MI">Michigan</option>
                	<option value="MN">Minnesota</option>
                	<option value="MS">Mississippi</option>
                	<option value="MO">Missouri</option>
                	<option value="MT">Montana</option>
                	<option value="NE">Nebraska</option>
                	<option value="NV">Nevada</option>
                	<option value="NH">New Hampshire</option>
                	<option value="NJ">New Jersey</option>
                	<option value="NM">New Mexico</option>
                	<option value="NY">New York</option>
                	<option value="NC">North Carolina</option>
                	<option value="ND">North Dakota</option>
                	<option value="OH">Ohio</option>
                	<option value="OK">Oklahoma</option>
                	<option value="OR">Oregon</option>
                	<option value="PA">Pennsylvania</option>
                	<option value="RI">Rhode Island</option>
                	<option value="SC">South Carolina</option>
                	<option value="SD">South Dakota</option>
                	<option value="TN">Tennessee</option>
                	<option value="TX">Texas</option>
                	<option value="UT">Utah</option>
                	<option value="VT">Vermont</option>
                	<option value="VA">Virginia</option>
                	<option value="WA">Washington</option>
                	<option value="WV">West Virginia</option>
                	<option value="WI">Wisconsin</option>
                	<option value="WY">Wyoming</option>
              </select>

              @if ($errors->has('state'))
                  <span class="help-block">
                      <strong>{{ $errors->first('state') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
          <label for="phone" class="col-md-4 control-label">Phone</label>

          <div class="col-md-6">
              <input id="phone" type="phone" class="form-control" name="phone" value="{{ old('phone') }}" required>

              @if ($errors->has('phone'))
                  <span class="help-block">
                      <strong>{{ $errors->first('phone') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('fax') ? ' has-error' : '' }}">
          <label for="fax" class="col-md-4 control-label">Fax</label>

          <div class="col-md-6">
              <input id="fax" type="phone" class="form-control" name="fax" value="{{ old('fax') }}">

              @if ($errors->has('fax'))
                  <span class="help-block">
                      <strong>{{ $errors->first('fax') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('tollFree') ? ' has-error' : '' }}">
          <label for="tollFree" class="col-md-4 control-label">Toll Free</label>

          <div class="col-md-6">
              <input id="tollFree" type="phone" class="form-control" name="tollFree" value="{{ old('tollFree') }}">

              @if ($errors->has('tollFree'))
                  <span class="help-block">
                      <strong>{{ $errors->first('tollFree') }}</strong>
                  </span>
              @endif
          </div>
      </div>
      @if(!isset($type))
      <div class="form-control">
          <button type="button" class="btn yellow cancel">Cancel</button>
          <button type="submit" form="main-form" class="btn green">Submit</button>
      </div>
      @endif
  </form>
</div>
<script>
$(".cancel").off("click").on("click", function(){
  $(".form-container").prev().removeClass("hidden");
  $(".form-container").removeClass("box");
  $(".form-container").html("");
});
</script>

resources/views/forms/userCreate.blade.php
<div class="form-wrapper">
  <form id="main-form" class="" method="POST" action="{{ route('users.store') }}">
      {{ csrf_field() }}
    
      <input id="type" class="hidden" name="type" value="{{$type}}" required autofocus>

      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
          <label for="name" class="col-md-4 control-label">Name</label>

          <div class="col-md-6">
              <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

              @if ($errors->has('name'))
                  <span class="help-block">
                      <strong>{{ $errors->first('name') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
          <label for="username" class="col-md-4 control-label">User Name</label>

          <div class="col-md-6">
              <input id="username" class="form-control" name="username" value="{{ old('username') }}" required>

              @if ($errors->has('username'))
                  <span class="help-block">
                      <strong>{{ $errors->first('username') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
          <label for="password" class="col-md-4 control-label">Password</label>

          <div class="col-md-6">
              <input id="password" type="password" class="form-control" name="password" required>

              @if ($errors->has('password'))
                  <span class="help-block">
                      <strong>{{ $errors->first('password') }}</strong>
                  </span>
              @endif
          </div>
      </div>

      <div class="form-group">
          <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

          <div class="col-md-6">
              <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
          </div>
      </div>
  </form>
</div>